### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by davvit** [tk120404/node-rssparser#35]
Hello, I was trying out this repo and i cant get it to build correctly.
bunch of error regarding node-gyp. 

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session e52d86570aa0326f
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall rssparser@0.0.10
7 info lifecycle rssparser@0.0.10~preinstall: rssparser@0.0.10
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 warn read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 http fetch GET 304 https://registry.npmjs.org/iconv 165ms (from cache)
15 silly pacote version manifest for iconv@2.1.11 fetched in 190ms
16 http fetch GET 304 https://registry.npmjs.org/nan 37ms (from cache)
17 silly pacote version manifest for nan@2.0.9 fetched in 39ms
18 silly install loadAllDepsIntoIdealTree
19 http fetch GET 304 https://registry.npmjs.org/vows 27ms (from cache)
20 silly pacote range manifest for vows@* fetched in 28ms
21 http fetch GET 304 https://registry.npmjs.org/glob 28ms (from cache)
22 silly pacote range manifest for glob@~4.0.6 fetched in 30ms
23 http fetch GET 304 https://registry.npmjs.org/graceful-fs 23ms (from cache)
24 silly pacote range manifest for graceful-fs@^3.0.2 fetched in 24ms
25 warn deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
26 http fetch GET 304 https://registry.npmjs.org/diff 65ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/eyes 66ms (from cache)
28 silly pacote range manifest for diff@~1.0.8 fetched in 66ms
29 silly pacote range manifest for eyes@~0.1.6 fetched in 66ms
30 http fetch GET 304 https://registry.npmjs.org/natives 31ms (from cache)
31 silly pacote range manifest for natives@^1.1.0 fetched in 33ms
32 http fetch GET 304 https://registry.npmjs.org/minimatch 62ms (from cache)
33 http fetch GET 304 https://registry.npmjs.org/inherits 63ms (from cache)
34 silly pacote range manifest for minimatch@^1.0.0 fetched in 63ms
35 warn deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
36 silly pacote range manifest for inherits@2 fetched in 65ms
37 http fetch GET 304 https://registry.npmjs.org/once 65ms (from cache)
38 silly pacote range manifest for once@^1.3.0 fetched in 66ms
39 http fetch GET 304 https://registry.npmjs.org/sigmund 26ms (from cache)
40 silly pacote range manifest for sigmund@~1.0.0 fetched in 27ms
41 http fetch GET 304 https://registry.npmjs.org/lru-cache 28ms (from cache)
42 silly pacote range manifest for lru-cache@2 fetched in 30ms
43 http fetch GET 304 https://registry.npmjs.org/wrappy 29ms (from cache)
44 silly pacote range manifest for wrappy@1 fetched in 30ms
45 silly pacote range manifest for vows@* fetched in 0ms
46 silly resolveWithNewModule vows@0.8.1 checking installable status
47 silly pacote range manifest for eyes@~0.1.6 fetched in 2ms
48 silly resolveWithNewModule eyes@0.1.8 checking installable status
49 silly pacote range manifest for diff@~1.0.8 fetched in 2ms
50 silly resolveWithNewModule diff@1.0.8 checking installable status
51 silly pacote range manifest for glob@~4.0.6 fetched in 2ms
52 silly resolveWithNewModule glob@4.0.6 checking installable status
53 silly pacote range manifest for graceful-fs@^3.0.2 fetched in 2ms
54 silly resolveWithNewModule graceful-fs@3.0.11 checking installable status
55 silly pacote range manifest for inherits@2 fetched in 2ms
56 silly resolveWithNewModule inherits@2.0.3 checking installable status
57 silly pacote range manifest for minimatch@^1.0.0 fetched in 3ms
58 silly resolveWithNewModule minimatch@1.0.0 checking installable status
59 silly pacote range manifest for once@^1.3.0 fetched in 3ms
60 silly resolveWithNewModule once@1.4.0 checking installable status
61 silly pacote range manifest for natives@^1.1.0 fetched in 0ms
62 silly resolveWithNewModule natives@1.1.1 checking installable status
63 silly pacote range manifest for lru-cache@2 fetched in 1ms
64 silly resolveWithNewModule lru-cache@2.7.3 checking installable status
65 silly pacote range manifest for sigmund@~1.0.0 fetched in 1ms
66 silly resolveWithNewModule sigmund@1.0.1 checking installable status
67 silly pacote range manifest for wrappy@1 fetched in 0ms
68 silly resolveWithNewModule wrappy@1.0.2 checking installable status
69 silly currentTree rssparser@0.0.10
69 silly currentTree +-- diff@1.0.8
69 silly currentTree +-- eyes@0.1.8
69 silly currentTree +-- glob@4.0.6
69 silly currentTree +-- graceful-fs@3.0.11
69 silly currentTree +-- inherits@2.0.3
69 silly currentTree +-- lru-cache@2.7.3
69 silly currentTree +-- minimatch@1.0.0
69 silly currentTree +-- natives@1.1.1
69 silly currentTree +-- once@1.4.0
69 silly currentTree +-- request@2.67.0
69 silly currentTree | +-- aws-sign2@0.6.0
69 silly currentTree | +-- bl@1.0.1
69 silly currentTree | | `-- readable-stream@2.0.5
69 silly currentTree | |   +-- core-util-is@1.0.2
69 silly currentTree | |   +-- inherits@2.0.1
69 silly currentTree | |   +-- isarray@0.0.1
69 silly currentTree | |   +-- process-nextick-args@1.0.6
69 silly currentTree | |   +-- string_decoder@0.10.31
69 silly currentTree | |   `-- util-deprecate@1.0.2
69 silly currentTree | +-- caseless@0.11.0
69 silly currentTree | +-- combined-stream@1.0.5
69 silly currentTree | | `-- delayed-stream@1.0.0
69 silly currentTree | +-- extend@3.0.0
69 silly currentTree | +-- forever-agent@0.6.1
69 silly currentTree | +-- form-data@1.0.0-rc3
69 silly currentTree | | `-- async@1.5.2
69 silly currentTree | +-- har-validator@2.0.6
69 silly currentTree | | +-- chalk@1.1.1
69 silly currentTree | | | +-- ansi-styles@2.1.0
69 silly currentTree | | | +-- escape-string-regexp@1.0.4
69 silly currentTree | | | +-- has-ansi@2.0.0
69 silly currentTree | | | | `-- ansi-regex@2.0.0
69 silly currentTree | | | +-- strip-ansi@3.0.0
69 silly currentTree | | | | `-- ansi-regex@2.0.0
69 silly currentTree | | | `-- supports-color@2.0.0
69 silly currentTree | | +-- commander@2.9.0
69 silly currentTree | | | `-- graceful-readlink@1.0.1
69 silly currentTree | | +-- is-my-json-valid@2.12.4
69 silly currentTree | | | +-- generate-function@2.0.0
69 silly currentTree | | | +-- generate-object-property@1.2.0
69 silly currentTree | | | | `-- is-property@1.0.2
69 silly currentTree | | | +-- jsonpointer@2.0.0
69 silly currentTree | | | `-- xtend@4.0.1
69 silly currentTree | | `-- pinkie-promise@2.0.0
69 silly currentTree | |   `-- pinkie@2.0.1
69 silly currentTree | +-- hawk@3.1.3
69 silly currentTree | | +-- boom@2.10.1
69 silly currentTree | | +-- cryptiles@2.0.5
69 silly currentTree | | +-- hoek@2.16.3
69 silly currentTree | | `-- sntp@1.0.9
69 silly currentTree | +-- http-signature@1.1.0
69 silly currentTree | | +-- assert-plus@0.1.5
69 silly currentTree | | +-- jsprim@1.2.2
69 silly currentTree | | | +-- extsprintf@1.0.2
69 silly currentTree | | | +-- json-schema@0.2.2
69 silly currentTree | | | `-- verror@1.3.6
69 silly currentTree | | `-- sshpk@1.7.3
69 silly currentTree | |   +-- asn1@0.2.3
69 silly currentTree | |   +-- assert-plus@0.2.0
69 silly currentTree | |   +-- dashdash@1.12.2
69 silly currentTree | |   +-- ecc-jsbn@0.1.1
69 silly currentTree | |   +-- jodid25519@1.0.2
69 silly currentTree | |   +-- jsbn@0.1.0
69 silly currentTree | |   `-- tweetnacl@0.13.3
69 silly currentTree | +-- is-typedarray@1.0.0
69 silly currentTree | +-- isstream@0.1.2
69 silly currentTree | +-- json-stringify-safe@5.0.1
69 silly currentTree | +-- mime-types@2.1.9
69 silly currentTree | | `-- mime-db@1.21.0
69 silly currentTree | +-- node-uuid@1.4.7
69 silly currentTree | +-- oauth-sign@0.8.0
69 silly currentTree | +-- qs@5.2.0
69 silly currentTree | +-- stringstream@0.0.5
69 silly currentTree | +-- tough-cookie@2.2.1
69 silly currentTree | `-- tunnel-agent@0.4.2
69 silly currentTree +-- sigmund@1.0.1
69 silly currentTree +-- underscore@1.8.3
69 silly currentTree +-- vows@0.8.1
69 silly currentTree +-- wrappy@1.0.2
69 silly currentTree `-- xml2js@0.4.16
69 silly currentTree   +-- sax@1.1.4
69 silly currentTree   `-- xmlbuilder@4.2.1
69 silly currentTree     `-- lodash@4.0.0
70 silly idealTree rssparser@0.0.10
70 silly idealTree +-- diff@1.0.8
70 silly idealTree +-- eyes@0.1.8
70 silly idealTree +-- glob@4.0.6
70 silly idealTree +-- graceful-fs@3.0.11
70 silly idealTree +-- iconv@2.1.11
70 silly idealTree | `-- nan@2.0.9
70 silly idealTree +-- inherits@2.0.3
70 silly idealTree +-- lru-cache@2.7.3
70 silly idealTree +-- minimatch@1.0.0
70 silly idealTree +-- natives@1.1.1
70 silly idealTree +-- once@1.4.0
70 silly idealTree +-- request@2.67.0
70 silly idealTree | +-- aws-sign2@0.6.0
70 silly idealTree | +-- bl@1.0.1
70 silly idealTree | | `-- readable-stream@2.0.5
70 silly idealTree | |   +-- core-util-is@1.0.2
70 silly idealTree | |   +-- inherits@2.0.1
70 silly idealTree | |   +-- isarray@0.0.1
70 silly idealTree | |   +-- process-nextick-args@1.0.6
70 silly idealTree | |   +-- string_decoder@0.10.31
70 silly idealTree | |   `-- util-deprecate@1.0.2
70 silly idealTree | +-- caseless@0.11.0
70 silly idealTree | +-- combined-stream@1.0.5
70 silly idealTree | | `-- delayed-stream@1.0.0
70 silly idealTree | +-- extend@3.0.0
70 silly idealTree | +-- forever-agent@0.6.1
70 silly idealTree | +-- form-data@1.0.0-rc3
70 silly idealTree | | `-- async@1.5.2
70 silly idealTree | +-- har-validator@2.0.6
70 silly idealTree | | +-- chalk@1.1.1
70 silly idealTree | | | +-- ansi-styles@2.1.0
70 silly idealTree | | | +-- escape-string-regexp@1.0.4
70 silly idealTree | | | +-- has-ansi@2.0.0
70 silly idealTree | | | | `-- ansi-regex@2.0.0
70 silly idealTree | | | +-- strip-ansi@3.0.0
70 silly idealTree | | | | `-- ansi-regex@2.0.0
70 silly idealTree | | | `-- supports-color@2.0.0
70 silly idealTree | | +-- commander@2.9.0
70 silly idealTree | | | `-- graceful-readlink@1.0.1
70 silly idealTree | | +-- is-my-json-valid@2.12.4
70 silly idealTree | | | +-- generate-function@2.0.0
70 silly idealTree | | | +-- generate-object-property@1.2.0
70 silly idealTree | | | | `-- is-property@1.0.2
70 silly idealTree | | | +-- jsonpointer@2.0.0
70 silly idealTree | | | `-- xtend@4.0.1
70 silly idealTree | | `-- pinkie-promise@2.0.0
70 silly idealTree | |   `-- pinkie@2.0.1
70 silly idealTree | +-- hawk@3.1.3
70 silly idealTree | | +-- boom@2.10.1
70 silly idealTree | | +-- cryptiles@2.0.5
70 silly idealTree | | +-- hoek@2.16.3
70 silly idealTree | | `-- sntp@1.0.9
70 silly idealTree | +-- http-signature@1.1.0
70 silly idealTree | | +-- assert-plus@0.1.5
70 silly idealTree | | +-- jsprim@1.2.2
70 silly idealTree | | | +-- extsprintf@1.0.2
70 silly idealTree | | | +-- json-schema@0.2.2
70 silly idealTree | | | `-- verror@1.3.6
70 silly idealTree | | `-- sshpk@1.7.3
70 silly idealTree | |   +-- asn1@0.2.3
70 silly idealTree | |   +-- assert-plus@0.2.0
70 silly idealTree | |   +-- dashdash@1.12.2
70 silly idealTree | |   +-- ecc-jsbn@0.1.1
70 silly idealTree | |   +-- jodid25519@1.0.2
70 silly idealTree | |   +-- jsbn@0.1.0
70 silly idealTree | |   `-- tweetnacl@0.13.3
70 silly idealTree | +-- is-typedarray@1.0.0
70 silly idealTree | +-- isstream@0.1.2
70 silly idealTree | +-- json-stringify-safe@5.0.1
70 silly idealTree | +-- mime-types@2.1.9
70 silly idealTree | | `-- mime-db@1.21.0
70 silly idealTree | +-- node-uuid@1.4.7
70 silly idealTree | +-- oauth-sign@0.8.0
70 silly idealTree | +-- qs@5.2.0
70 silly idealTree | +-- stringstream@0.0.5
70 silly idealTree | +-- tough-cookie@2.2.1
70 silly idealTree | `-- tunnel-agent@0.4.2
70 silly idealTree +-- sigmund@1.0.1
70 silly idealTree +-- underscore@1.8.3
70 silly idealTree +-- vows@0.8.1
70 silly idealTree +-- wrappy@1.0.2
70 silly idealTree `-- xml2js@0.4.16
70 silly idealTree   +-- sax@1.1.4
70 silly idealTree   `-- xmlbuilder@4.2.1
70 silly idealTree     `-- lodash@4.0.0
71 silly install generateActionsToTake
72 silly diffTrees action count 2
73 silly diffTrees add nan@2.0.9
74 silly diffTrees add iconv@2.1.11
75 silly decomposeActions action count 16
76 silly decomposeActions fetch nan@2.0.9
77 silly decomposeActions extract nan@2.0.9
78 silly decomposeActions preinstall nan@2.0.9
79 silly decomposeActions build nan@2.0.9
80 silly decomposeActions install nan@2.0.9
81 silly decomposeActions postinstall nan@2.0.9
82 silly decomposeActions finalize nan@2.0.9
83 silly decomposeActions refresh-package-json nan@2.0.9
84 silly decomposeActions fetch iconv@2.1.11
85 silly decomposeActions extract iconv@2.1.11
86 silly decomposeActions preinstall iconv@2.1.11
87 silly decomposeActions build iconv@2.1.11
88 silly decomposeActions install iconv@2.1.11
89 silly decomposeActions postinstall iconv@2.1.11
90 silly decomposeActions finalize iconv@2.1.11
91 silly decomposeActions refresh-package-json iconv@2.1.11
92 silly install executeActions
93 silly doSerial global-install 16
94 verbose correctMkdir C:\Users\boobs\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
95 verbose lock using C:\Users\boobs\AppData\Roaming\npm-cache\_locks\staging-2dacb3dfe951e23b.lock for D:\workspace\node-rssparser\node_modules\.staging
96 silly doParallel extract 16
97 silly extract nan@2.0.9
98 silly pacote trying nan@https://registry.npmjs.org/nan/-/nan-2.0.9.tgz by hash: sha1-0Cp3D0Z3iELM65ThfKsx/8cjSgU=
99 silly extract iconv@2.1.11
100 silly pacote trying iconv@https://registry.npmjs.org/iconv/-/iconv-2.1.11.tgz by hash: sha1-X12pOmQ1BvXOqovZx41hdPi5NRo=
101 silly pacote nan@https://registry.npmjs.org/nan/-/nan-2.0.9.tgz extracted to D:\workspace\node-rssparser\node_modules\.staging\nan-3ac7c7ed by content address 27ms
102 silly pacote iconv@https://registry.npmjs.org/iconv/-/iconv-2.1.11.tgz extracted to D:\workspace\node-rssparser\node_modules\.staging\iconv-5e18aa31 by content address 113ms
103 silly doReverseSerial unbuild 16
104 silly doSerial remove 16
105 silly doSerial move 16
106 silly doSerial finalize 16
107 silly finalize D:\workspace\node-rssparser\node_modules\iconv\node_modules\nan
108 silly finalize D:\workspace\node-rssparser\node_modules\iconv
109 silly doParallel refresh-package-json 16
110 silly refresh-package-json D:\workspace\node-rssparser\node_modules\iconv\node_modules\nan
111 silly refresh-package-json D:\workspace\node-rssparser\node_modules\iconv
112 silly doParallel preinstall 16
113 silly preinstall nan@2.0.9
114 info lifecycle nan@2.0.9~preinstall: nan@2.0.9
115 silly preinstall iconv@2.1.11
116 info lifecycle iconv@2.1.11~preinstall: iconv@2.1.11
117 silly doSerial build 16
118 silly build nan@2.0.9
119 info linkStuff nan@2.0.9
120 silly linkStuff nan@2.0.9 has D:\workspace\node-rssparser\node_modules\iconv\node_modules as its parent node_modules
121 verbose linkBins nan@2.0.9
122 verbose linkMans nan@2.0.9
123 silly build iconv@2.1.11
124 info linkStuff iconv@2.1.11
125 silly linkStuff iconv@2.1.11 has D:\workspace\node-rssparser\node_modules as its parent node_modules
126 verbose linkBins iconv@2.1.11
127 verbose linkMans iconv@2.1.11
128 silly doSerial global-link 16
129 silly doParallel update-linked 16
130 silly doSerial install 16
131 silly install nan@2.0.9
132 info lifecycle nan@2.0.9~install: nan@2.0.9
133 silly install iconv@2.1.11
134 info lifecycle iconv@2.1.11~install: iconv@2.1.11
135 verbose lifecycle iconv@2.1.11~install: unsafe-perm in lifecycle true
136 verbose lifecycle iconv@2.1.11~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\workspace\node-rssparser\node_modules\iconv\node_modules\.bin;D:\workspace\node-rssparser\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\boobs\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\boobs\AppData\Roaming\npm
137 verbose lifecycle iconv@2.1.11~install: CWD: D:\workspace\node-rssparser\node_modules\iconv
138 silly lifecycle iconv@2.1.11~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
139 silly lifecycle iconv@2.1.11~install: Returned: code: 1  signal: null
140 info lifecycle iconv@2.1.11~install: Failed to exec install script
141 verbose unlock done using C:\Users\boobs\AppData\Roaming\npm-cache\_locks\staging-2dacb3dfe951e23b.lock for D:\workspace\node-rssparser\node_modules\.staging
142 silly saveTree rssparser@0.0.10
142 silly saveTree +-- iconv@2.1.11
142 silly saveTree | `-- nan@2.0.9
142 silly saveTree +-- request@2.67.0
142 silly saveTree | +-- aws-sign2@0.6.0
142 silly saveTree | +-- bl@1.0.1
142 silly saveTree | | `-- readable-stream@2.0.5
142 silly saveTree | |   +-- core-util-is@1.0.2
142 silly saveTree | |   +-- inherits@2.0.1
142 silly saveTree | |   +-- isarray@0.0.1
142 silly saveTree | |   +-- process-nextick-args@1.0.6
142 silly saveTree | |   +-- string_decoder@0.10.31
142 silly saveTree | |   `-- util-deprecate@1.0.2
142 silly saveTree | +-- caseless@0.11.0
142 silly saveTree | +-- combined-stream@1.0.5
142 silly saveTree | | `-- delayed-stream@1.0.0
142 silly saveTree | +-- extend@3.0.0
142 silly saveTree | +-- forever-agent@0.6.1
142 silly saveTree | +-- form-data@1.0.0-rc3
142 silly saveTree | | +-- async@1.5.2
142 silly saveTree | | `-- mime-types@2.1.9
142 silly saveTree | |   `-- mime-db@1.21.0
142 silly saveTree | +-- har-validator@2.0.6
142 silly saveTree | | +-- chalk@1.1.1
142 silly saveTree | | | +-- ansi-styles@2.1.0
142 silly saveTree | | | +-- escape-string-regexp@1.0.4
142 silly saveTree | | | +-- has-ansi@2.0.0
142 silly saveTree | | | | `-- ansi-regex@2.0.0
142 silly saveTree | | | +-- strip-ansi@3.0.0
142 silly saveTree | | | | `-- ansi-regex@2.0.0
142 silly saveTree | | | `-- supports-color@2.0.0
142 silly saveTree | | +-- commander@2.9.0
142 silly saveTree | | | `-- graceful-readlink@1.0.1
142 silly saveTree | | +-- is-my-json-valid@2.12.4
142 silly saveTree | | | +-- generate-function@2.0.0
142 silly saveTree | | | +-- generate-object-property@1.2.0
142 silly saveTree | | | | `-- is-property@1.0.2
142 silly saveTree | | | +-- jsonpointer@2.0.0
142 silly saveTree | | | `-- xtend@4.0.1
142 silly saveTree | | `-- pinkie-promise@2.0.0
142 silly saveTree | |   `-- pinkie@2.0.1
142 silly saveTree | +-- hawk@3.1.3
142 silly saveTree | | +-- boom@2.10.1
142 silly saveTree | | | `-- hoek@2.16.3
142 silly saveTree | | +-- cryptiles@2.0.5
142 silly saveTree | | +-- hoek@2.16.3
142 silly saveTree | | `-- sntp@1.0.9
142 silly saveTree | +-- http-signature@1.1.0
142 silly saveTree | | +-- assert-plus@0.1.5
142 silly saveTree | | +-- jsprim@1.2.2
142 silly saveTree | | | +-- extsprintf@1.0.2
142 silly saveTree | | | +-- json-schema@0.2.2
142 silly saveTree | | | `-- verror@1.3.6
142 silly saveTree | | `-- sshpk@1.7.3
142 silly saveTree | |   +-- asn1@0.2.3
142 silly saveTree | |   +-- assert-plus@0.2.0
142 silly saveTree | |   +-- dashdash@1.12.2
142 silly saveTree | |   +-- ecc-jsbn@0.1.1
142 silly saveTree | |   | `-- jsbn@0.1.0
142 silly saveTree | |   +-- jodid25519@1.0.2
142 silly saveTree | |   +-- jsbn@0.1.0
142 silly saveTree | |   `-- tweetnacl@0.13.3
142 silly saveTree | +-- is-typedarray@1.0.0
142 silly saveTree | +-- isstream@0.1.2
142 silly saveTree | +-- json-stringify-safe@5.0.1
142 silly saveTree | +-- mime-types@2.1.9
142 silly saveTree | +-- node-uuid@1.4.7
142 silly saveTree | +-- oauth-sign@0.8.0
142 silly saveTree | +-- qs@5.2.0
142 silly saveTree | +-- stringstream@0.0.5
142 silly saveTree | +-- tough-cookie@2.2.1
142 silly saveTree | `-- tunnel-agent@0.4.2
142 silly saveTree +-- underscore@1.8.3
142 silly saveTree +-- vows@0.8.1
142 silly saveTree | +-- diff@1.0.8
142 silly saveTree | +-- eyes@0.1.8
142 silly saveTree | `-- glob@4.0.6
142 silly saveTree |   +-- graceful-fs@3.0.11
142 silly saveTree |   | `-- natives@1.1.1
142 silly saveTree |   +-- inherits@2.0.3
142 silly saveTree |   +-- minimatch@1.0.0
142 silly saveTree |   | +-- lru-cache@2.7.3
142 silly saveTree |   | `-- sigmund@1.0.1
142 silly saveTree |   `-- once@1.4.0
142 silly saveTree |     `-- wrappy@1.0.2
142 silly saveTree `-- xml2js@0.4.16
142 silly saveTree   +-- sax@1.1.4
142 silly saveTree   `-- xmlbuilder@4.2.1
142 silly saveTree     `-- lodash@4.0.0
143 warn rssparser@0.0.10 No license field.
144 verbose stack Error: iconv@2.1.11 install: `node-gyp rebuild`
144 verbose stack Exit status 1
144 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
144 verbose stack     at emitTwo (events.js:126:13)
144 verbose stack     at EventEmitter.emit (events.js:214:7)
144 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
144 verbose stack     at emitTwo (events.js:126:13)
144 verbose stack     at ChildProcess.emit (events.js:214:7)
144 verbose stack     at maybeClose (internal/child_process.js:925:16)
144 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
145 verbose pkgid iconv@2.1.11
146 verbose cwd D:\workspace\node-rssparser
147 verbose Windows_NT 10.0.16299
148 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
149 verbose node v8.9.4
150 verbose npm  v5.6.0
151 error code ELIFECYCLE
152 error errno 1
153 error iconv@2.1.11 install: `node-gyp rebuild`
153 error Exit status 1
154 error Failed at the iconv@2.1.11 install script.
154 error This is probably not a problem with npm. There is likely additional logging output above.
155 verbose exit [ 1, true ]
`

**Comment by tk120404** [comment]
Fixed. Please try
